// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList histEq_param[]={
 {"intensity",offsetof(histEq,intensity),"float",ADM_param_float},
 {"chroma",offsetof(histEq,chroma),"bool",ADM_param_bool},
{NULL,0,NULL}
};
