// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "histEq.h"
bool  histEq_jserialize(const char *file, const histEq *key){
admJson json;
json.addFloat("intensity",key->intensity);
json.addBool("chroma",key->chroma);
return json.dumpToFile(file);
};
bool  histEq_jdeserialize(const char *file, const ADM_paramList *tmpl,histEq *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
